import type { Signal } from '../../../alive-constitution/contracts';

/**
 * Event bus for internal autonomic signals.
 *
 * Internal signals are generated by autonomic subsystems (health monitor,
 * anomaly detection, resource monitor). All must be routed through
 * alive-runtime STG verification before reaching cognition.
 */
export function emitInternalSignal(
  partialSignal: Omit<Signal, 'id'>
): Signal {
  return {
    ...partialSignal,
    id: crypto.randomUUID(),
  };
}
