import type { Signal } from '../../../alive-constitution/contracts/signal';
import { getSignalId } from '../../../alive-constitution/contracts/signal';

/**
 * PATCH 1: Event bus for internal autonomic signals.
 *
 * Internal signals are those generated by autonomic subsystems (health monitor,
 * anomaly detection, resource monitor) rather than from external input.
 * All internal signals must be routed through STG verification before reaching cognition.
 */

/**
 * Emit an internal signal from an autonomic subsystem.
 *
 * @param partialSignal - Signal data without id/signal_id (they will be generated)
 * @returns Complete Signal object marked as internal and unverified
 *
 * The returned signal MUST be routed through alive-runtime/router/signal-router.ts
 * to receive STG verification before being processed by cognition.
 */
export function emitInternalSignal(
  partialSignal: Omit<Signal, 'id' | 'signal_id' | 'origin' | 'stg_verified' | 'binding_complete'>
): Signal {
  const id = crypto.randomUUID();

  return {
    ...partialSignal,
    id,
    signal_id: id,
    origin: 'internal',  // Mark source as internal autonomic system
    stg_verified: false,  // Default: unverified until STG gate approves
    binding_complete: false,  // Default: binding not yet complete
  };
}
